Mobile portfolio
Bushido-brown/My-Portfolio pull request #1
Opened 2022-03-18 18:22 UTC by Bushido-brown

2022-03-18 19:29 UTC, vic778 requested changes
### STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @Bushido-brown , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Project highlights:
- [x] All linter checks are passing :heavy_check_mark: 
- [x] Descriptive commits and correct use of the Git Flow :fire:
- [x] :white_check_mark: page titles :white_check_mark: text headings :white_check_mark: color contrast :white_check_mark: resize :white_check_mark: basic structure of the page 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


![so close](https://c.tenor.com/nMbdSNsg_jsAAAAC/the-simpsons-homer-simpson.gif)

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 19:29 UTC, vic778 commented on styles/style.css
> +}
kindly delete these lines because there empty

2022-03-18 19:29 UTC, vic778 commented on index.html
> +</html>
kindly you need to fix your margin and your padding. there is too much space between your footer and the end of the page. please make sure you're following he [Figma](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/images/m1_setup/headline-mobile.png) design. inspect the page to know the padding and the margin of your template in Figma. often it is symbolized by a `*`

2022-03-18 21:39 UTC, Kingstalux reviewed
Hi @Bushido-brown , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966](https://user-images.githubusercontent.com/85113567/159086221-60338d54-bb1a-4301-87b8-abb6ace6f54e.gif)



## Invalid Code Review Request 🛑 


- [ ] You have submitted a project that does not have the linters checks. Kindly configure your linters correctly and make sure the checks show up on GitHub and they should be passing before requesting for a review 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-19 02:50 UTC, smunozmo requested changes
Hi @Bushido-brown, 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

<img src="https://media1.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 02:50 UTC, smunozmo commented on index.html
> +        <img src="/img/socialmediaicons.png" alt="#">
[OPTIONAL] This `img` is not working, just correct the file name.

2022-03-19 02:50 UTC, smunozmo commented on index.html
> +</html>
- [ ] Great job removing the unncessary code, however, your padding and margin is still looking fairly different from the original design:

Template: 
![Captura de pantalla 2022-03-18 a la(s) 9 43 21 p  m](https://user-images.githubusercontent.com/83717285/159103834-8ffc631c-c8e2-4307-a407-c10ead67898f.png)

Your design:
![Captura de pantalla 2022-03-18 a la(s) 9 43 39 p  m](https://user-images.githubusercontent.com/83717285/159103848-df265806-70f1-46a9-96e4-fb5f8d95efc8.png)

Please address this problem and you will be done! 💯

2022-03-19 12:41 UTC, BenMukebo approved these changes
### Hi @Bushido-brown , 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

<img src="https://media3.giphy.com/media/W2b8JkhIwnVH7Sr1zl/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 13:34 UTC, merged