add index.html for mobile-portfolio
Bushido-brown/My-Portfolio pull request #2
Opened 2022-03-25 16:28 UTC by Bushido-brown

2022-03-25 18:11 UTC, Kingstalux reviewed
Hi @Bushido-brown , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966](https://user-images.githubusercontent.com/85113567/160177664-29363eae-d1e1-4cb7-b525-9a251bb51aa9.gif)


## Invalid Code Review Request 🛑 

You have submitted a project, that does not meet the minimum requirements.
- [ ] Kindly provide a detailed pull request description that provides information on the changes made in this pull request.
- [ ] Kindly remove all empty sections from your README file to make it more professional 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-25 19:03 UTC, Kingstalux requested changes
Hi @Bushido-brown , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966](https://user-images.githubusercontent.com/85113567/160185152-2ef275e0-1298-4cd8-b2b1-693c12167378.gif)


## Highlights
✅ Good commit messages
✅ Linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 19:03 UTC, Kingstalux commented on index.html
> +    <link rel="stylesheet" href="/My-Portfolio/styles/style.css" />
- [ ] Kindly provide the correct path for your styles which is `href="/styles/style.css"`. Right now none of your styles are showing.
- Your site:
![Annotation 2022-03-25 192941](https://user-images.githubusercontent.com/85113567/160181882-426edede-ebe7-4225-9d30-f2b4d0abff3a.jpg)

2022-03-25 19:03 UTC, Kingstalux commented on index.html
> +          <img src="/My-Portfolio/img/Icons/Union.png" alt="#" />
- [ ] Kindly provide the correct path to all your images as right now none of your images are displaying. It is probably due to the `/My-Portfolio/` that you added at the start of the image source URL. Kindly correct that. Below is a video of how your page looks like
- Your site:
![Animation](https://user-images.githubusercontent.com/85113567/160182846-92f22336-0e5e-455a-bddb-77ac40009476.gif)

2022-03-25 19:03 UTC, Kingstalux commented on index.html
> +              <div>2015</div>
- Kindly apply the following to all your project cards 👍 
- [ ] Provide the correct URL to all the images and make sure they are displaying well 😄 
- [ ] Kindly use an `h2` or `h3` tag for the heading of each card instead of the generic `div` tag for best semantic practices 👍 
- [ ] Kindly center your cards on your site so as to follow the Figma design

2022-03-25 19:03 UTC, Kingstalux commented on index.html
> +          <button class="button">See Project</button>
- [ ] It would be great if you could apply the button interactions to all the buttons on your site for a better user interface 
- Button interactions:
![Annotation 2022-03-25 195053](https://user-images.githubusercontent.com/85113567/160183608-a6b35617-2ab0-4e8c-b0e0-bb5b208f5114.jpg)

2022-03-25 19:03 UTC, Kingstalux commented on index.html
> +      <div class="container1">
- [ ] Kindly use a `section` tag for this section instead of the generic `div` tag for best semantic practices 👍 
- [ ] Also, the space between the last project card and the `About` section is too large as seen in the video above. Kindly reduce that so as to match the Figma template.

2022-03-25 19:03 UTC, Kingstalux commented on index.html
> +        <h1 class="box4">About Myself</h1>
- [ ] Your site should have only one `h1` tag which should be the main heading of your page. Kindly use an `h2` tag here 😄 
- [ ] Also, this heading should take two lines instead of one line as shown in the template
- [ ] It would be great if you could apply the correct font weight also 💯 
- Your design:
![Annotation 2022-03-25 195709](https://user-images.githubusercontent.com/85113567/160184407-37bc74d1-5908-445e-a3b5-843135b4d651.jpg)
- Figma design:
![Annotation 2022-03-25 195719](https://user-images.githubusercontent.com/85113567/160184449-aacafef3-2ea7-4d89-b44a-60b0d0cae99d.jpg)

2022-03-25 19:03 UTC, Kingstalux commented on index.html
> +        <p class="box6">LET'S CONNECT</p>
- [ ] This text `Let's Connect` is a heading and as a result, should use an `hx` tag like an `h2` or `h3` tag. Kindly rectify this issue

2022-03-25 19:03 UTC, Kingstalux commented on index.html
> +          </div>
- There are some issues with this last part that also need to be iron out 👍 
- [ ] The technology categories ("Languages", "Frameworks" and "Skills") should be placed in a `ul`, each of them in a `li`.
- [ ] The technology in each category(e.g., "JavasScript", "HTML" and "CSS") should also be a list `ul` and each of them a `li`
- [ ] Kindly apply the correct font weight to all elements in this section 👍

2022-03-26 20:18 UTC, AmaduKamara approved these changes
# Status: Approved 🎈🎈🎈

Hi @Bushido-brown,

Good job in making all the changes requested by the previous reviewer. You're doing great 👍👍👍

![ClappingLeonardoDicaprioGIF](https://user-images.githubusercontent.com/50941074/160255439-52b13689-92a3-4a45-b803-6a0f584a48e8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

[ Optional Changes ]

- [ ] Kindly adjust the spacing I marked in red circles on the screenshot as I compare them with the Figma design

** Your Design **
1. 
![image](https://user-images.githubusercontent.com/50941074/160255554-c8e3c534-5a35-4d79-9d22-9c3f029a7a99.png)
2.
![image](https://user-images.githubusercontent.com/50941074/160255584-9fcf9065-48c5-44ee-92e7-17db2d76d327.png)

** Figma Design **
1.
![image](https://user-images.githubusercontent.com/50941074/160255601-e6782781-fb21-4b73-b542-d58b752dde94.png)
2.
![image](https://user-images.githubusercontent.com/50941074/160255619-5ea1113f-193c-4942-a94d-d1a267f4d17a.png)

- [ ]  Kindly work on those changes as they will make your project look great and very similar to the Figma design
- [ ] Please see the green highlight I did on the Figma designs and adjust your project to look exactly like the one in the Figma desig. You work on those changes, you'll be good in your next milestone, and will save you a lot of hassles next week. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-27 09:21 UTC, merged